### ISSUE TITLE
Error: 100: Invalid API Key (Key has invalid format)

### ISSUE THREAD

**Issue by PatrickBK** [jschementi/flickr_photostream_sorter#7]
Hi,

I followed procedure and this is the result when I run flickr_photostream_sorter

MacBook-Pro-van-Patrick:~ patrickboskessen$ flickr_photostream_sorter
Traceback (most recent call last):
  File "/usr/local/bin/flickr_photostream_sorter", line 9, in <module>
    load_entry_point('flickr-photostream-sorter==0.1.1', 'console_scripts', 'flickr_photostream_sorter')()
  File "/Library/Python/2.7/site-packages/flickr_photostream_sorter/__init__.py", line 17, in main
    (token, frob) = flickr.get_token_part_one(perms='write')
  File "/Library/Python/2.7/site-packages/flickrapi/__init__.py", line 758, in get_token_part_one
    rsp = self.auth_getFrob(auth_token=None, format='xmlnode')
  File "/Library/Python/2.7/site-packages/flickrapi/__init__.py", line 357, in handler
    parse_format=args['format'], **args)
  File "/Library/Python/2.7/site-packages/flickrapi/__init__.py", line 444, in __wrap_in_parser
    return parser(self, data)
  File "/Library/Python/2.7/site-packages/flickrapi/__init__.py", line 263, in parse_xmlnode
    raise FlickrError(u'Error: %(code)s: %(msg)s' % err)
flickrapi.exceptions.FlickrError: Error: 100: Invalid API Key (Key has invalid format)
MacBook-Pro-van-Patrick:~ patrickboskessen$

Did I miss anything?

**Comment by PatrickBK** [comment]
fixed this issue by altering .bash_profile. The example echo code to add Flickr access info, wasn't correct, too many spaces, no quotes.

It needs to be like... 

export FLICKR_API_KEY="123key"
export FLICKR_SECRET="123secret"

**Comment by PatrickBK** [comment]
the tool now doesn't work because Flickr opens in Safari but doesn't ask permission for anything, it just shows the Flickr homepage.

**Comment by SBFRF** [comment]
I have similar to this from firefox.  I'm not sure what "authorize means" when the webpage pops up it seems to be the home page ... I looked around the flickr page and couldn't find any specific things to ''authorize'' then ran the code anyway and came up with the following error.  The errors look related to the flickr api python module any help would be helpful!!!!
@alexanderrenaud keep an eye on this 

    [spike@cloudbreak~/CMTB]$ flickr_photostream_sorter
        Press ENTER after you authorized this program
    Traceback (most recent call last):
      File "/opt/anaconda2/bin/flickr_photostream_sorter", line 11, in <module>
        sys.exit(main())
      File "/opt/anaconda2/lib/python2.7/site-packages/flickr_photostream_sorter/__init__.py", line 21, in main
        token = flickr.get_token_part_two((token, frob))
      File "/opt/anaconda2/lib/python2.7/site-packages/flickrapi/__init__.py", line 778, in get_token_part_two
        return self.get_token(frob)
      File "/opt/anaconda2/lib/python2.7/site-packages/flickrapi/__init__.py", line 786, in get_token
        rsp = self.auth_getToken(frob=frob, auth_token=None, format='xmlnode')
      File "/opt/anaconda2/lib/python2.7/site-packages/flickrapi/__init__.py", line 357, in handler
        parse_format=args['format'], **args)
      File "/opt/anaconda2/lib/python2.7/site-packages/flickrapi/__init__.py", line 444, in __wrap_in_parser
        return parser(self, data)
      File "/opt/anaconda2/lib/python2.7/site-packages/flickrapi/__init__.py", line 263, in parse_xmlnode
        raise FlickrError(u'Error: %(code)s: %(msg)s' % err)
    flickrapi.exceptions.FlickrError: Error: 108: Invalid frob`
